# Generated by Django 2.0.4 on 2018-11-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.FloatField(),
        ),
    ]
