var child = [
  { 'dupe': false, 'type': 4, 'name': 'accounts', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost:8000/accounts/', 'fetched': true, 'code': 404, 'len': 3973, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': true, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0xfe077ff9 },
  { 'dupe': false, 'type': 4, 'name': 'admin', 'dir': 'c1', 'linked': 5, 'url': 'http://localhost:8000/admin/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 10, 'issue_cnt': [ 3, 1, 1, 0, 0 ], 'sig': 0x5296a400 },
  { 'dupe': false, 'type': 4, 'name': 'history', 'dir': 'c2', 'linked': 5, 'url': 'http://localhost:8000/history/', 'fetched': true, 'code': 200, 'len': 1921, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 2, 1, 0, 0 ], 'sig': 0xdf0ed7ff },
  { 'dupe': false, 'type': 4, 'name': 'history', 'dir': 'c3', 'linked': 2, 'url': 'http://localhost:8000/history/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xdef2f368 },
  { 'dupe': true, 'type': 4, 'name': 'history', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost:8000/history/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c6', 'linked': 5, 'url': 'http://localhost:8000/login/', 'fetched': true, 'code': 200, 'len': 882, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 4, 2, 0, 0, 0 ], 'sig': 0x955b81e1 },
  { 'dupe': false, 'type': 4, 'name': 'logout', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost:8000/logout/', 'fetched': true, 'code': 200, 'len': 403, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xdf0d1a37 },
  { 'dupe': false, 'type': 4, 'name': 'register', 'dir': 'c8', 'linked': 5, 'url': 'http://localhost:8000/register/', 'fetched': true, 'code': 200, 'len': 3545, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 8, 'issue_cnt': [ 2, 1, 0, 0, 0 ], 'sig': 0x83900a0e },
  { 'dupe': false, 'type': 4, 'name': 'static', 'dir': 'c9', 'linked': 2, 'url': 'http://localhost:8000/static/', 'fetched': true, 'code': 404, 'len': 1634, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': true, 'child_cnt': 7, 'issue_cnt': [ 17, 0, 0, 0, 0 ], 'sig': 0x1ad1965a },
  { 'dupe': false, 'type': 4, 'name': 'transfer', 'dir': 'c10', 'linked': 5, 'url': 'http://localhost:8000/transfer/', 'fetched': true, 'code': 200, 'len': 1122, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0x4a13f06f }
];
