var child = [
  { 'dupe': false, 'type': 128, 'name': '8ziCF6LAfVpHPYAKu5tI3POOm0BOvuhWyz4SaEGENEq41s0DR7FXH74grGgSGfag', 'dir': 'c0', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=8ziCF6LAfVpHPYAKu5tI3POOm0BOvuhWyz4SaEGENEq41s0DR7FXH74grGgSGfag&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'glRrqigDKbEI1y5Oyz7rElVfAnQYhBRkGlDHVQbHiUF5d2vHVBjGiDbHF3v2smKE', 'dir': 'c1', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=glRrqigDKbEI1y5Oyz7rElVfAnQYhBRkGlDHVQbHiUF5d2vHVBjGiDbHF3v2smKE&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'HQLRL1QDpqoobpLt9QMDgm0FKtKdpW8X7Qx7gzLHX9pLnTbmwSYSUEg7P9phAH1h', 'dir': 'c2', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=HQLRL1QDpqoobpLt9QMDgm0FKtKdpW8X7Qx7gzLHX9pLnTbmwSYSUEg7P9phAH1h&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'Lg891N8QorbYEaoxWC0KWueKpxYjQ1UfbgUpwl3UWaclQEOqjEcZAMucudDn1MNz', 'dir': 'c3', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=Lg891N8QorbYEaoxWC0KWueKpxYjQ1UfbgUpwl3UWaclQEOqjEcZAMucudDn1MNz&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'NCeumfZcnWR5a0qA3rQ8ra0WRWbthVS7dC0KRNUgVFSsmuQtqt2n5sgoWCQxsGLr', 'dir': 'c4', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=NCeumfZcnWR5a0qA3rQ8ra0WRWbthVS7dC0KRNUgVFSsmuQtqt2n5sgoWCQxsGLr&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'OdorxGfSrZuD1moEIgbuu8AkbRuu5WBSedaH2eaWZIv0dQOx5inJ8qQMgx9ygHuc', 'dir': 'c5', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=OdorxGfSrZuD1moEIgbuu8AkbRuu5WBSedaH2eaWZIv0dQOx5inJ8qQMgx9ygHuc&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'toqxA3tg4ygF5KJEN8NKXzZkvtheEuftTocN5BokChh2he9xaaZZBRfMA9WiPf8N', 'dir': 'c6', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=toqxA3tg4ygF5KJEN8NKXzZkvtheEuftTocN5BokChh2he9xaaZZBRfMA9WiPf8N&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'x5GDtSaQOwpwyRYzhWx9Ronxo3nhfVJmX5sTYq5UmfqTKlosEYJovGDZtJ2lqGCG', 'dir': 'c7', 'linked': 0, 'url': 'http://localhost:8000/admin/login/ DATA:csrfmiddlewaretoken=x5GDtSaQOwpwyRYzhWx9Ronxo3nhfVJmX5sTYq5UmfqTKlosEYJovGDZtJ2lqGCG&username=Smith&password=skipfish&next=/admin/', 'fetched': true, 'code': 200, 'len': 2157, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 }
];
