# Generated by Django 2.1.4 on 2018-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
